#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/c/Users/ouarda/Desktop/The ocr thing/AdamimOCR_Django/adamim_front/node_modules/.pnpm/yarn@1.22.22/node_modules/yarn/bin/node_modules:/mnt/c/Users/ouarda/Desktop/The ocr thing/AdamimOCR_Django/adamim_front/node_modules/.pnpm/yarn@1.22.22/node_modules/yarn/node_modules:/mnt/c/Users/ouarda/Desktop/The ocr thing/AdamimOCR_Django/adamim_front/node_modules/.pnpm/yarn@1.22.22/node_modules:/mnt/c/Users/ouarda/Desktop/The ocr thing/AdamimOCR_Django/adamim_front/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/c/Users/ouarda/Desktop/The ocr thing/AdamimOCR_Django/adamim_front/node_modules/.pnpm/yarn@1.22.22/node_modules/yarn/bin/node_modules:/mnt/c/Users/ouarda/Desktop/The ocr thing/AdamimOCR_Django/adamim_front/node_modules/.pnpm/yarn@1.22.22/node_modules/yarn/node_modules:/mnt/c/Users/ouarda/Desktop/The ocr thing/AdamimOCR_Django/adamim_front/node_modules/.pnpm/yarn@1.22.22/node_modules:/mnt/c/Users/ouarda/Desktop/The ocr thing/AdamimOCR_Django/adamim_front/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../bin/yarn.js" "$@"
else
  exec node  "$basedir/../../bin/yarn.js" "$@"
fi
